# Generated by Django 6.0.6 on 2026-06-16 15:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('id_codigo', models.CharField(blank=True, max_length=100, unique=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad_original', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unidad', models.CharField(choices=[('kg', 'Kilogramos'), ('g', 'Gramos'), ('ml', 'Mililitros'), ('l', 'Litros'), ('unidad', 'Unidad'), ('docena', 'Docena')], default='kg', max_length=20)),
                ('fecha_entrada', models.DateTimeField(auto_now_add=True)),
                ('fecha_expiracion', models.DateField()),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-fecha_entrada'],
            },
        ),
        migrations.CreateModel(
            name='EstadisticasUso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uso_promedio_diario', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('insumo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='estadisticas', to='inventario.insumo')),
            ],
        ),
        migrations.CreateModel(
            name='AlertaMensaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('vencimiento', 'Vencimiento próximo'), ('expirado', 'Producto expirado'), ('bajo_stock', 'Stock bajo'), ('info', 'Información general')], default='info', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('activa', models.BooleanField(default=True)),
                ('insumo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='inventario.insumo')),
            ],
            options={
                'verbose_name_plural': 'Alertas y Mensajes',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='UsoHistorico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_usada', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True)),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='inventario.insumo')),
            ],
            options={
                'verbose_name_plural': 'Usos Históricos',
                'ordering': ['-fecha'],
            },
        ),
    ]
