# Generated by Django 6.0.6 on 2026-06-16 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='id_codigo',
            field=models.IntegerField(blank=True, editable=False, null=True, unique=True),
        ),
    ]
